title:              Marcelo Laprea
email:              marcelojosel15@gmail.com
description:        Software Engineering Blog
author:             Marcelo Laprea
baseurl:            "/"
url:                "https://lapreamarcelo.github.io"

# Social Profiles
twitter_username:   marcelolaprea
github_username:    lapreamarcelo
linkedin_username:  marcelolaprea

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
