# SITE CONFIGURATION
baseurl: "/"
url: "https://lapreamarcelo.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Marcelo Laprea                                                                          # site's title
description: "Software Engineer blog, including iOS, Swift, Xcode, Machine Learning tutorials" # used by search engines
avatar: https://lapreamarcelo.github.io/assets/img/triangle.png                                # Empty for no avatar in navbar
favicon: https://lapreamarcelo.github.io/assets/favicon.ico                                     # Icon displayed in the tab

# Header and footer text
header_text: Marcelo Laprea  # Change Blog header text
header_feature_image: assets/img/gray.jpg
footer_text: Created by <a href="https://avilatek.co/" target="_blank">Avila Tek</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: https://lapreamarcelo.github.io/assets/img/lineart.png  # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics: "UA-156419394-1"                      # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
